services:
  torchserve:
    build:
      context: ./ad_fast_api/torchserve
      dockerfile: ./torchserve.Dockerfile
    expose:
      - 8080
      - 8081
    # ports:
    #   - 8080:8080
    #   - 8081:8081
    # restart: always
    # deploy:
    #   resources:
    #     limits:
    #       cpus: 0.5
    #       memory: 64g
    networks:
      ad_server: {}

  animated_drawings:
    build:
      context: ./ad_fast_api/animated_drawings
      dockerfile: ./animated_drawings.Dockerfile
      args:
        WORK_DIR: ${ROOT_DIR}
        INTERNAL_PORT: ${ANIMATED_DRAWINGS_INTERNAL_PORT}
        ANIMATED_DRAWINGS_WORKSPACE_DIR: ${ANIMATED_DRAWINGS_WORKSPACE_DIR}
    expose:
      - ${ANIMATED_DRAWINGS_INTERNAL_PORT}
    volumes:
      - ./ad_fast_api/ad_fast_api/workspace/files:/${ROOT_DIR}/${ANIMATED_DRAWINGS_WORKSPACE_DIR}/files
      - ./ad_fast_api/ad_fast_api/workspace/config:/${ROOT_DIR}/${ANIMATED_DRAWINGS_WORKSPACE_DIR}/config
    # restart: always
    # deploy: 
    #   resources:
    #     limits:
    #       cpus: 0.5
          # memory: 64g
    networks:
      ad_server: {}

  ad_fast_api:
    build:
      context: ./ad_fast_api
      dockerfile: ./ad_fast_api.Dockerfile
      args:
        WORK_DIR: ${ROOT_DIR}
        INTERNAL_PORT: ${AD_FAST_API_INTERNAL_PORT}
        ANIMATED_DRAWINGS_WORKSPACE_DIR: ${ANIMATED_DRAWINGS_WORKSPACE_DIR}
    ports:
      - ${AD_FAST_API_EXTERNAL_PORT}:${AD_FAST_API_INTERNAL_PORT}
    volumes:
      - ./ad_fast_api/ad_fast_api:/${ROOT_DIR}/ad_fast_api
    # restart: always
    # deploy:
    #   resources:
    #     limits:
    #       cpus: 0.5
          # memory: 64g
    networks:
      ad_server: {}

networks:
  ad_server:
    name: ${NETWORK_NAME}
    driver: bridge