version: '3.8'

services:
  torchserve:
    container_name: torchserve
    build:
      context: ./AnimatedDrawingsAPI/sources/torchserve/
      dockerfile: Dockerfile
    expose:
      - 8080
      - 8081

  animated_drawings:
    depends_on:
      - torchserve
    container_name: animated_drawings
    build:
      context: .
      dockerfile: ./AnimatedDrawingsAPI/animated_drawings.Dockerfile
    expose:
      - 8001
    volumes:
      - ./AnimatedDrawingsAPI:/mycode/AnimatedDrawingsAPI
      - /mnt/sdb1/ad_db/files:/mycode/files
    entrypoint: conda run --no-capture-output -n animated_drawings python -u /mycode/AnimatedDrawingsAPI/main.py

  ad_fast_api:
    depends_on:
      - animated_drawings
    container_name: ad_fast_api
    build:
      context: .
      dockerfile: ./ADFastAPI/ad_fast_api.Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./ADFastAPI:/mycode/ADFastAPI
      - /mnt/sdb1/ad_db/files:/mycode/files
    entrypoint: python /mycode/ADFastAPI/main.py