version: '3.8'

services:
  torchserve:
    container_name: torchserve
    build:
      context: ./AnimatedDrawings/torchserve
      dockerfile: Dockerfile
    expose:
      - 8080
      - 8081

  animated_drawings:
    depends_on:
      - torchserve
    container_name: animated_drawings
    build:
      context: .
      dockerfile: ./animated_drawings_docker/animated_drawings.Dockerfile
    expose:
      - 8001
    volumes:
      - ./AnimatedDrawings:/mycode/AnimatedDrawings
    entrypoint: conda run --no-capture-output -n animated_drawings python -u animated_drawings_api.py
  
  db:
    depends_on:
      - animated_drawings
    image: postgres:15.3
    container_name: ad_db
    restart: always
    environment:
      POSTGRES_DB: ad_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - /mnt/sdb1/ad_db/postgres:/var/lib/postgresql/data

  ad_fast_api:
    depends_on:
      - db
    container_name: ad_fast_api
    build:
      context: .
      dockerfile: ./ad_fast_api_docker/ad_fast_api.Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./ADFastAPI:/mycode/ADFastAPI
      - /mnt/sdb1/ad_db/files:/mycode/files
    entrypoint: python /mycode/ADFastAPI/main.py