services:
  torchserve:
    container_name: torchserve
    build:
      context: ./AnimatedDrawingsAPI/sources/torchserve/
      dockerfile: Dockerfile
    expose:
      - 8080
      - 8081
    networks:
      - ad_server

  animated_drawings:
    depends_on:
      - torchserve
    container_name: animated_drawings
    build:
      context: .
      dockerfile: ./AnimatedDrawingsAPI/animated_drawings.Dockerfile
    expose:
      - 8001
    volumes:
      - ./AnimatedDrawingsAPI:/mycode/AnimatedDrawingsAPI
      - ./files:/mycode/files
    entrypoint: conda run --no-capture-output -n animated_drawings python -u /mycode/AnimatedDrawingsAPI/main.py
    networks:
      - ad_server

  ad_fast_api:
    depends_on:
      - animated_drawings
    container_name: ad_fast_api
    build:
      context: .
      dockerfile: ./ADFastAPI/ad_fast_api.Dockerfile
    ports:
      - ${EXTERNAL_PORT}:8000
    volumes:
      - ./ADFastAPI:/mycode/ADFastAPI
      - ./files:/mycode/files
    entrypoint: python /mycode/ADFastAPI/main.py
    networks:
      - ad_server

networks:
  ad_server:
    name: ad_server
    driver: bridge