services:
  torchserve:
    build:
      context: ./animated_drawings/AnimatedDrawings/torchserve/
      dockerfile: Dockerfile
    # expose:
    #   - 8080
    #   - 8081
    ports:
      - 8080:8080
      - 8081:8081
    # restart: always
    # deploy:
    #   resources:
    #     limits:
    #       cpus: 0.5
    #       memory: 64g
    networks:
      ad_server: {}

  animated_drawings:
    build:
      context: ./animated_drawings
      dockerfile: ./animated_drawings.Dockerfile
      args:
        WORK_DIR: ${ROOT_DIR}
        INTERNAL_PORT: ${ANIMATED_DRAWINGS_INTERNAL_PORT}
        ANIMATED_DRAWINGS_WORKSPACE_DIR: ${ANIMATED_DRAWINGS_WORKSPACE_DIR}
    # expose:
    #   - ${ANIMATED_DRAWINGS_INTERNAL_PORT}
    ports:
    - ${ANIMATED_DRAWINGS_INTERNAL_PORT}:${ANIMATED_DRAWINGS_INTERNAL_PORT}
    volumes:
      - ./animated_drawings/AnimatedDrawings:/${ROOT_DIR}/AnimatedDrawings
      # - ./workspace:/${ROOT_DIR}/${ANIMATED_DRAWINGS_WORKSPACE_DIR}
      - ./workspace:/${ROOT_DIR}/AnimatedDrawings/${ANIMATED_DRAWINGS_WORKSPACE_DIR}
    # restart: always
    # deploy:
    #   resources:
    #     limits:
    #       cpus: 0.5
          # memory: 64g
    networks:
      ad_server: {}

  ad_fast_api:
    # depends_on:
    #   - animated_drawings
    build:
      context: ./ad_fast_api
      dockerfile: ./ad_fast_api.Dockerfile
      args:
        WORK_DIR: ${ROOT_DIR}
        INTERNAL_PORT: ${AD_FAST_API_INTERNAL_PORT}
        ANIMATED_DRAWINGS_WORKSPACE_DIR: ${ANIMATED_DRAWINGS_WORKSPACE_DIR}
    ports:
      - ${AD_FAST_API_EXTERNAL_PORT}:${AD_FAST_API_INTERNAL_PORT}
    volumes:
      - ./ad_fast_api:/${ROOT_DIR}/ad_fast_api
      - ./workspace/files:/${ROOT_DIR}/ad_fast_api/ad_fast_api/workspace/files
    # restart: always
    # deploy:
    #   resources:
    #     limits:
    #       cpus: 0.5
          # memory: 64g
    networks:
      ad_server: {}

networks:
  ad_server:
    name: ${NETWORK_NAME}
    driver: bridge