"""empty message

Revision ID: 71ea19b718f7
Revises: e29ac31e84b5
Create Date: 2023-07-16 13:07:45.221083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71ea19b718f7'
down_revision = 'e29ac31e84b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
