"""empty message

Revision ID: 9a995dda639b
Revises: e6c735217c99
Create Date: 2023-06-26 13:03:21.709748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a995dda639b'
down_revision = 'e6c735217c99'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AnimatedDrawings', sa.Column('cropped_image_url', sa.String(), nullable=True))
    op.drop_column('AnimatedDrawings', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AnimatedDrawings', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('AnimatedDrawings', 'cropped_image_url')
    # ### end Alembic commands ###
