"""empty message

Revision ID: 010a7c7c072a
Revises: a718c9cef7cf
Create Date: 2023-07-16 07:34:37.062282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '010a7c7c072a'
down_revision = 'a718c9cef7cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AnimatedDrawings', sa.Column('masked_image_url', sa.String(), nullable=True))
    op.drop_column('AnimatedDrawings', 'cropped_image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AnimatedDrawings', sa.Column('cropped_image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('AnimatedDrawings', 'masked_image_url')
    # ### end Alembic commands ###
