"""rename class

Revision ID: a718c9cef7cf
Revises: 9a995dda639b
Create Date: 2023-06-27 07:45:27.786391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a718c9cef7cf'
down_revision = '9a995dda639b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
