"""empty message

Revision ID: e29ac31e84b5
Revises: 010a7c7c072a
Create Date: 2023-07-16 11:50:55.613360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e29ac31e84b5'
down_revision = '010a7c7c072a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AnimatedDrawings', sa.Column('annotations_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('AnimatedDrawings', 'annotations_url')
    # ### end Alembic commands ###
